import {
  Activity,
  ArrowRight,
  ArrowUpRight,
  Award,
  Bed,
  Bot,
  Brain,
  Baby,
  Building2,
  Calendar,
  CheckCircle2,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ClipboardList,
  Clock,
  Compass,
  CreditCard,
  Dna,
  Droplet,
  Facebook,
  FileCheck,
  FileSearch,
  FileText,
  FlaskConical,
  Flower2,
  Globe,
  GraduationCap,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hexagon,
  Instagram,
  Languages,
  Layers,
  Linkedin,
  Mail,
  MapPin,
  Menu,
  Mic,
  Microscope,
  Pause,
  Phone,
  Plane,
  Play,
  Plus,
  Quote,
  Radiation,
  Ribbon,
  Search,
  SearchCheck,
  Shield,
  ShieldPlus,
  Sparkles,
  Sprout,
  Stethoscope,
  Sun,
  Target,
  Users,
  User,
  UserCheck,
  UserSearch,
  Video,
  Wind,
  X,
  Youtube,
  type LucideIcon,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  activity: Activity,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  award: Award,
  bed: Bed,
  bot: Bot,
  brain: Brain,
  baby: Baby,
  building: Building2,
  calendar: Calendar,
  check: Check,
  "check-circle": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "clipboard-list": ClipboardList,
  clock: Clock,
  compass: Compass,
  "credit-card": CreditCard,
  dna: Dna,
  droplet: Droplet,
  facebook: Facebook,
  "file-check": FileCheck,
  "file-search": FileSearch,
  "file-text": FileText,
  flask: FlaskConical,
  "flask-conical": FlaskConical,
  flower: Flower2,
  globe: Globe,
  "graduation-cap": GraduationCap,
  heart: Heart,
  "heart-handshake": HeartHandshake,
  "heart-pulse": HeartPulse,
  hexagon: Hexagon,
  instagram: Instagram,
  languages: Languages,
  layers: Layers,
  linkedin: Linkedin,
  mail: Mail,
  "map-pin": MapPin,
  menu: Menu,
  mic: Mic,
  microscope: Microscope,
  pause: Pause,
  phone: Phone,
  plane: Plane,
  play: Play,
  plus: Plus,
  quote: Quote,
  radiation: Radiation,
  ribbon: Ribbon,
  search: Search,
  "search-check": SearchCheck,
  shield: Shield,
  "shield-plus": ShieldPlus,
  sparkles: Sparkles,
  sprout: Sprout,
  stethoscope: Stethoscope,
  sun: Sun,
  target: Target,
  users: Users,
  user: User,
  "user-check": UserCheck,
  "user-search": UserSearch,
  video: Video,
  wind: Wind,
  x: X,
  youtube: Youtube,
};

export function Icon({
  name,
  className,
  strokeWidth = 1.75,
  "aria-hidden": ariaHidden = true,
  style,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
  "aria-hidden"?: boolean;
  style?: React.CSSProperties;
}) {
  const Cmp = map[name] ?? Ribbon;
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden={ariaHidden} style={style} />;
}
